###################
### KEYBINDINGS ###
###################

# Apps keybindings
bind = $appBind, f, exec, ~/.config/hypr/extra/scripts/openormove.sh class:$browser $browser
bind = $appBind, d, exec, ~/.config/hypr/extra/scripts/openormove.sh class:$discord $discord
bind = $appBind, o, exec, prime-run osu-lazer
bind = $appBind, a, exec, anki
bind = $appBind, k, exec, $menu
bind = $appBind, t, exec, tetrio-desktop
bind = $appBind, p, exec, ~/.config/hypr/extra/scripts/openormove.sh class:Spotify $onlinemusicplayer
bind = $appBind, m, exec, thunderbird
bind = $appBind, g, exec, xrandr --output DP-1 --primary && steam &
bind = $appBind, n, exec, ~/.config/hypr/extra/scripts/openormove.sh class:Logseq logseq
bind = $appBind, w, exec, pkill waybar && waybar &

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Space, exec, $menu
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, O, exec, ~/.config/hypr/extra/scripts/hyprlock.sh
bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, S, layoutmsg, togglesplit
bind = $mainMod, T, pin, 
bind = $mainMod, I, exec, rofi-network-manager 
bind = $mainMod, F, fullscreen, 1
bind = $mainMod, D, exec, wpctl set-mute -p $(hyprctl activewindow -j | jq '.pid') toggle
bind = $mainMod, N, exec, makoctl dismiss -a
bind = $mainMod, N, exec, notify-send "Notification sent!" "This is a notification"
bind = $mainMod, N, exec, makoctl reload
bind = $mainMod, M, exec, /home/burrs/.config/hypr/extra/scripts/inputmute.sh
bind = $mainMod, C, exec, makoctl dismiss -a

# Move focus with mainMod
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod , Tab, cyclenext, float
bind = $mainMod SHIFT, Tab, cyclenext, prevfloat

# Switch workspaces with mainMod + [0-9]
# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 1
bind = $mainMod, 2, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 2
bind = $mainMod, 3, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 3
bind = $mainMod, 4, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 4
bind = $mainMod, 5, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 5
bind = $mainMod, 6, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 6
bind = $mainMod, 7, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 7
bind = $mainMod, 8, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 8
bind = $mainMod, 9, exec, ~/.config/hypr/extra/scripts/moveworkspace.sh 9
bind = $mainMod, 0, togglespecialworkspace, scratch

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $moveToWorkspace, 1, movetoworkspace, 1
bind = $moveToWorkspace, 2, movetoworkspace, 2
bind = $moveToWorkspace, 3, movetoworkspace, 3
bind = $moveToWorkspace, 4, movetoworkspace, 4
bind = $moveToWorkspace, 5, movetoworkspace, 5
bind = $moveToWorkspace, 6, movetoworkspace, 6
bind = $moveToWorkspace, 7, movetoworkspace, 7
bind = $moveToWorkspace, 8, movetoworkspace, 8
bind = $moveToWorkspace, 9, movetoworkspace, 9
bind = $moveToWorkspace, 0, movetoworkspace, special:scratch

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
