# Miscallaneous, kind of windows pilled


bind = , F11, fullscreen, 
bind = ALT, F4, killactive,
bind = CTRL ALT, T, exec, $terminal

# Visit the most recent workspace
bind = ALT, tab, workspace, previous

# Screenshot
bindl = SUPER SHIFT , s, exec, ~/.config/hypr/extra/scripts/screenshot.sh
bindl = SUPER SHIFT , o, exec, bash ~/.config/hypr/extra/scripts/ocr.sh

# Wlogout
# bindi = , code:202, exec, pgrep -x wlogout >/dev/null || wlogout --margin-left 600 --margin-right 600 --margin-bottom 325 --margin-top 325 
# bindi = , code:202, exec, mpv /home/burrs/.config/hypr/extra/sfx/Wii/Home/Sample_0002.wav
bindi = , code:202, exec, ~/.config/hypr/extra/scripts/wlogout.sh


bind = CTRL ALT, delete, exec, ~/.config/hypr/extra/scripts/wlogout.sh
# Send notification
