bind = SUPER, r, submap, resize

submap = resize

binde = , right, resizeactive, 100 0
binde = , left, resizeactive, -100 0
binde = , up, resizeactive, 0 100
binde = , down, resizeactive, 0 -100
binde = , l, resizeactive, 100 0
binde = , h, resizeactive, -100 0
binde = , j, resizeactive, 0 100
binde = , k, resizeactive, 0 -100

binde = SHIFT, left,  moveactive, -50 0
binde = SHIFT, right, moveactive,  50 0
binde = SHIFT, up,    moveactive,  0 -50
binde = SHIFT, down,  moveactive,  0  50
binde = SHIFT, h,  moveactive, -50 0
binde = SHIFT, l,  moveactive,  50 0
binde = SHIFT, k,  moveactive,  0 -50
binde = SHIFT, j,  moveactive,  0  50

binde = ALT, left,  movewindow, l
binde = ALT, right, movewindow, r
binde = ALT, up,    movewindow, u
binde = ALT, down,  movewindow, d
binde = ALT, h,  movewindow, l
binde = ALT, l,  movewindow, r
binde = ALT, k,  movewindow, u
binde = ALT, j,  movewindow, d

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# source = "/home/burrs/.config/hypr/extra/binds/general.conf" # TODO:this doesnt work but probably does in lua lol

bind = , w, sendshortcut, , e
bind = , e, sendshortcut, , w

bind = , u, pass
bind = , escape, submap, reset
bind = , q, submap, reset

bind = , catchall, submap, resize
submap = reset
