# Changing Output with Multimedia Keys
# bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+ --limit 2.0

bindel = ,XF86AudioRaiseVolume, exec, sh -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+ --limit 2.0 && vol=\$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf \"%d%%\", \$2*100}') && hyprctl dismissnotify 1 && hyprctl notify 1 2000 0 \"Volume: \$vol\""
bindel = ,XF86AudioLowerVolume, exec, sh -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%- --limit 1.0 && vol=\$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf \"%d%%\", \$2*100}') && hyprctl dismissnotify 1 && hyprctl notify 1 2000 0 \"Volume: \$vol\""

# Changing Input with Multimedia Keys
bindeli = , XF86AudioMute, exec, /home/burrs/.config/hypr/extra/scripts/outputmute.sh
bindeli = , mouse:279, exec, /home/burrs/.config/hypr/extra/scripts/inputmute.sh
bindeli = , code:201, exec, /home/burrs/.config/hypr/extra/scripts/inputmute.sh

# Brightness - External monitor also included
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
bindel = ,XF86MonBrightnessUp, exec, ddcutil setvcp 10 + 10 # external monitor
bindel = ,XF86MonBrightnessDown, exec, ddcutil setvcp 10 - 10
