local m = require("src.model")
local funcs = require("src.funcs")
local st = m.singleTasks
local wt = m.weeklyTask
local yt = m.yearlyTask
local wt5 = function(name)
	return wt(name, 5)
end
return {
	wt("shave"),
	wt("check emails"),
	wt("nix flake update"),
	wt5("clean"),
	wt5("cut nails"),
	wt5("clear tabs"),
	wt5("clean toothbrush"),
	wt5("laundry"),
	{
		name = m.just("Humble Bundle"),
		conditions = { m.isDayOfWeek(2), m.isWeekOfMonth(1, m.timedelta(0, -17)) },
		-- -17 cause PST is 17 hours behind my time zone, its actually wednesday too
		duetime = m.dueTime(m.timedelta(30)),
		checkstart = function(date)
			return funcs.floorToDay(date) - m.timedelta(31) + m.timedelta(0, 3)
			-- 3 hours cause 3 am
		end,
		checkrepeats = m.justRepeats(2),
		finishdelta = m.just(m.timedelta(0)),
	},
	yt("Firmware Update (fwupd)"),
	yt("Wash Backpack"),
	-- m.multiWeekTask("exercise", { 0, 1, 3, 5, 6, 7 }),
	m.multiWeekTask("exercise", { 0, 1, 3, 5, 6}),
	st({
		"Test works",
		"bin scripts instead of hypr nixos",
		"neovim config (vim pack) treesit (ctrl backspace)",
		"declarative flatpak/roblox",
		"lua library lsp lazydev",
		"millenium nix",
		"steam notifications wayland work",
		"humble bundle tasks",
		"Stitch pants",
		"cadetship",
		"git fetch to burrsgs",
		"vanguard stocks, jk government bonds",
		"move games to wishlist steam",
		"clean megumin pillow",
		"wakeup checklist",
		"anu cssa",
		"Integrate gaussian distribution e^-x^2",
		"Proportional derivative controller engn",
		"vpython nix",
		"Go through emails",
		"gum cli addage to todo",
		"Go through all todo in taskmanger",
		"bsides/csides canberra",
		"Ctrl Backspace nvim",
		"get logseq todo in this",
		"message tax file number and supperannuation",
		"pullup tower",
		"task manager flake (check notes)",
		"make/add scripts folder (check notes)",
		"Find a way to use old numbers/uni psw",
		"android text writing app instead of firefox",
		"turn task manager into flake(check notes)",
		"another rip in pants",
		"add attributes list to tasks(check notes)",
		"find the anthony edwards defense video olympics",
		"Change tetrio pfp",
		"change android wallpaper",
		"Donate clothes",
		"accumulate tasks (check notes)",
		"home manager (replace stow)",
		"debloat computer",
		"shellnix/devenvs",
		"gitignore vesktop and fonts",
		"wlrwhichkey and submaps for opening apps",
		"Package my pomodoro script",
		"abuse the welfare system",
		"change fonts for all default programs.",
		"pomodoro program(check notes)",
		"macros logseq",
		"bitwarden/shitwarden or proton",
		"remove json5",
		"neomutt",
		"logseq and hyprland clear notofications keybind",
		"do something about burrsgs",
		"weekly tasks check notes",
		"replace goonroll",
		"buy gloves",
		"burrsgs pull/push confirmation",
		"replace phone alarm",
		"package micromouse",
		"rustlings",
		"test1",
		"test1",
		"Music task idea(check notes)",
		"Package all anki addons. (cn)",
		"remove neovim text wrapper.",
		"raspberry pi alarm (cn)",
		"task luarc json",
		"firmwareupdate task",
		"packages anki addons (cn)",
		"package luarocks",
		"osu",
		"burrsgs (cn)",
		"seasonal trackmania task",
		"laundry task",
		"efficient morning routine",
		"fuck youtube",
		"clean phone (task maybe)",
		"gymtask",
		"hyprland lua",
		"sheets pillowcase task",
		"home manager (cn)",
		"nvim per project exrc",
		"yearly task wash bag",
	}),
}
